# Generated by Django 5.1.7 on 2025-03-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10)),
                ('orientation', models.CharField(max_length=10)),
                ('window_size', models.CharField(choices=[('normal', 'Normal'), ('small', 'Small')], max_length=10)),
                ('furniture', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('occupied', 'Occupied'), ('vacant', 'Vacant'), ('unused', 'Unused'), ('others', 'Others')], max_length=10)),
            ],
        ),
    ]
