# Generated by Django 5.1.7 on 2025-03-26 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(blank=True, max_length=10, null=True)),
                ('orientation', models.CharField(blank=True, max_length=10, null=True)),
                ('window_size', models.CharField(blank=True, choices=[('normal', 'Normal'), ('small', 'Small')], max_length=10, null=True)),
                ('furniture', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('occupied', 'Occupied'), ('vacant', 'Vacant'), ('unused', 'Unused'), ('others', 'Others')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nick_name', models.CharField(blank=True, max_length=50, null=True)),
                ('checkin_date', models.DateField(blank=True, null=True)),
                ('payment_due_date', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('parking_spot', models.BooleanField(blank=True, default=False, null=True)),
                ('room', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms_app.room')),
            ],
        ),
    ]
