# Generated by Django 5.1.7 on 2025-04-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(blank=True, choices=[('occupied', 'Occupied'), ('occupiedpark', 'OccupiedPark'), ('vacant', 'Vacant'), ('unused', 'Unused'), ('others', 'Others')], max_length=15, null=True),
        ),
    ]
