# Generated by Django 5.1.7 on 2025-03-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0002_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='nick_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='parking_spot',
            field=models.BooleanField(default=False),
        ),
    ]
