# Generated by Django 5.1.7 on 2025-03-15 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0003_alter_tenant_middle_name_alter_tenant_nick_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms_app.room'),
        ),
    ]
