# Generated by Django 5.1.7 on 2025-03-15 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0004_tenant_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tenant',
            old_name='paymentdue_date',
            new_name='payment_due_date',
        ),
    ]
