# Generated by Django 5.1.7 on 2025-03-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0005_rename_paymentdue_date_tenant_payment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='checkin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
