# Generated by Django 5.1.7 on 2025-03-15 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0006_alter_tenant_checkin_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='parking_spot',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
