# Generated by Django 5.1.7 on 2025-03-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0007_alter_tenant_parking_spot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='parking_spot',
            field=models.BooleanField(default=False),
        ),
    ]
