# Generated by Django 5.1.7 on 2025-03-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms_app', '0008_alter_tenant_parking_spot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='window_size',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('small', 'Small')], max_length=10, null=True),
        ),
    ]
